### ISSUE TITLE
Couchdb.Connector.Reader undefined function

### ISSUE THREAD

**Issue by hikerninja** [mkrogemann/bird_watch#1]
@mkrogemann Excellent tutorial\example project.  I used this to help get a start on a json api, but ran into the following:

Trying to get a doc from couchdb by id was resulting in the following error:
`(UndefinedFunctionError) undefined function Couchdb.Connector.Reader.read/2`

This is stemming from couchdb.exs

`def read id do`
`{:ok, bird_json} = Reader.read @database_properties, id`
`bird_json`
`end`

The Reader.read function should be changed to the Reader.get function per the [couchdb_connector api-reference](https://hexdocs.pm/couchdb_connector/Couchdb.Connector.Reader.html)

`def read id do`
`{:ok, bird_json} = Reader.get @database_properties, id`
`bird_json`
`end`

**Comment by mkrogemann** [comment]
You are quite right. An embarrassing bit of left-over code from the time before the couchdb_connector API was finalized for its first release.
Thank you for pointing this out and for your nice feedback!
